repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: "https://github.com/Anadea/pre-commit-config-shellcheck"
    rev: "0.3.4"
    hooks:
      - id: "pre-commit-config-shellcheck"
